--------------------------------------------------------------------------------
-- js-writers.lua: routines creating client js code
-- This file is a part of pk-tools library
-- Copyright (c) Alexander Gladysh <ag@logiceditor.com>
-- Copyright (c) Dmitry Potapov <dp@logiceditor.com>
-- See file `COPYRIGHT` for the license
--------------------------------------------------------------------------------

local make_loggers = import 'pk-core/log.lua' { 'make_loggers' }
local log, dbg, spam, log_error = make_loggers("js-writers", "JSW")

--------------------------------------------------------------------------------

local arguments,
      optional_arguments,
      method_arguments
      = import 'lua-nucleo/args.lua'
      {
        'arguments',
        'optional_arguments',
        'method_arguments'
      }

local Q, CR, NPAD, write_file_using_template
      = import 'admin-gen/misc.lua'
      {
        'Q', 'CR', 'NPAD', 'write_file_using_template'
      }

--------------------------------------------------------------------------------

local write_navigator = function(game_model_data, navigator_template_filename, filename_out)
  local values = {}

  values.HEADER = [[
////////////////////////////////////////////////////////////////////////////////
// modules/navigator.js: main menu bar
////////////////////////////////////////////////////////////////////////////////
// WARNING! Do not change manually.
// Generated by generate-js.lua
////////////////////////////////////////////////////////////////////////////////

]]

  values.ADMINISTRATING = [[{
            text: I18N('Users'),
            handler: function() { PK.navigation.go_to_topic("admin_accounts"); }
          },
          {
            text: I18N('User profiles'),
            handler: function() { PK.navigation.go_to_topic("admin_profiles"); }
          }, "-",
          {
            text: I18N('View log'),
            handler: function() { PK.navigation.go_to_topic("log"); }
          }
]]

  values.USER_PROFILES_WHICH_CAN_EDIT_ALL = [[case 'administrator':
        case 'manager':
        case 'server_programmer':
]]

  values.USER_PROFILES_WHICH_CAN_EDIT_ONLY_GAME_DATA = [[case 'client_programmer':
        case 'game_designer':
]]

  values.GAME_MODEL_DATA = game_model_data

  write_file_using_template(
    values,
    filename_out,
    navigator_template_filename
  )
end

--------------------------------------------------------------------------------

local write_table_view = function(
    name, primary_key, custom_tbar,
    read_only_data, append_only_data, prohibit_deletion,
    columns,
    tv_template_filename,
    dir_out
  )
  local values = {}

  values.HEADER = [[
////////////////////////////////////////////////////////////////////////////////
// modules/tv_]] .. name .. [[: table view for game model data
////////////////////////////////////////////////////////////////////////////////
// WARNING! Do not change manually.
// Generated by generate-js.lua
////////////////////////////////////////////////////////////////////////////////

]]

  values.TITLE = 'I18N("tv_' .. name .. '")'
  values.TOPIC_NAME = Q("tv_" .. name)
  values.NAME = Q(name)
  values.PRIMARY_KEY = Q(primary_key)
  values.CUSTOM_TBAR = custom_tbar
  values.READ_ONLY_DATA = read_only_data and 'true' or 'false'
  values.APPEND_ONLY_DATA = append_only_data and 'true' or 'false'
  values.PROHIBIT_DELETION = prohibit_deletion and 'true' or 'false'
  values.TABLE_ELEMENT_EDITOR = Q("tee_" .. name)
  values.HANDLER = Q(name)
  values.COLUMNS = columns

  write_file_using_template(
    values,
    dir_out .. "modules/topics/tv_" .. name .. ".js",
    tv_template_filename
  )
end

local write_table_element_editor = function(name, primary_key, custom_tbar, properties, tee_template_filename, dir_out)
  local values = {}

  values.HEADER = [[
////////////////////////////////////////////////////////////////////////////////
// modules/tee_]] .. name .. [[: table element editor for game model data
////////////////////////////////////////////////////////////////////////////////
// WARNING! Do not change manually.
// Generated by generate-js.lua
////////////////////////////////////////////////////////////////////////////////

]]

  values.TITLE = 'I18N("tee_' .. name .. '")'
  values.TOPIC_NAME = Q("tee_" .. name)
  values.PRIMARY_KEY = Q(primary_key)
  values.TABLE_VIEW_TOPIC_NAME = Q("tv_" .. name)
  values.EXISTING_ITEM_TITLE = 'I18N("Existing item of ' .. name .. '")'
  values.NEW_ITEM_TITLE = 'I18N("New item of ' .. name .. '")'
  values.HANDLER = Q(name)
  values.CUSTOM_TBAR = custom_tbar
  values.PROPERTIES = properties

  write_file_using_template(
    values,
    dir_out .. "modules/topics/tee_" .. name .. ".js",
    tee_template_filename
  )
end

--------------------------------------------------------------------------------

local write_serialized_list_view = function(
    name, serialized_list_name, primary_key, columns,
    slv_template_filename,
    dir_out
  )

  local full_name = name .. '-' .. serialized_list_name

  local values = {}

  values.HEADER = [[
////////////////////////////////////////////////////////////////////////////////
// modules/tv_]] .. full_name .. [[: table view for serialized game model data
////////////////////////////////////////////////////////////////////////////////
// WARNING! Do not change manually.
// Generated by generate-js.lua
////////////////////////////////////////////////////////////////////////////////

]]

  values.TITLE = 'I18N("tv_sl_' .. full_name .. '")'
  values.TOPIC_NAME = Q("tv_sl_" .. full_name)
  values.PRIMARY_KEY = Q(primary_key)
  values.TABLE_ELEMENT_EDITOR = Q("tee_sl_" .. full_name)
  values.HANDLER = Q(full_name)
  values.COLUMNS = columns

  write_file_using_template(
    values,
    dir_out .. "modules/topics/tv_sl_" .. full_name .. ".js",
    slv_template_filename
  )
end

local write_serialized_list_element_editor = function(
    name, serialized_list_name, primary_key, properties,
    slee_template_filename,
    dir_out
  )

  local full_name = name .. '-' .. serialized_list_name

  local values = {}

  values.HEADER = [[
////////////////////////////////////////////////////////////////////////////////
// modules/tee_]] .. full_name .. [[: table element editor for serialized game model data
////////////////////////////////////////////////////////////////////////////////
// WARNING! Do not change manually.
// Generated by generate-js.lua
////////////////////////////////////////////////////////////////////////////////

]]

  values.TITLE = 'I18N("tee_sl_' .. full_name .. '")'
  values.TOPIC_NAME = Q("tee_sl_" .. full_name)
  values.PRIMARY_KEY = Q(primary_key)
  values.TABLE_VIEW_TOPIC_NAME = Q("tv_sl_" .. full_name)
  values.EXISTING_ITEM_TITLE = 'I18N("Existing item of ' .. full_name .. '")'
  values.NEW_ITEM_TITLE = 'I18N("New item of ' .. full_name .. '")'
  values.HANDLER = Q(full_name)
  values.PROPERTIES = properties

  write_file_using_template(
    values,
    dir_out .. "modules/topics/tee_sl_" .. full_name .. ".js",
    slee_template_filename
  )
end

--------------------------------------------------------------------------------

return
{
  write_navigator = write_navigator;
  write_table_view = write_table_view;
  write_table_element_editor = write_table_element_editor;
  write_serialized_list_view = write_serialized_list_view;
  write_serialized_list_element_editor = write_serialized_list_element_editor;
}
